import sys
sys_input=sys.stdin.readline

mos=dict()

mos['.-']='A'
mos['-...']='B'
mos['-.-.']='C'
mos['-..']='D'
mos['.']='E'
mos['..-.']='F'
mos['--.']='G'
mos['....']='H'
mos['..']='I'
mos['.---']='J'
mos['-.-']='K'
mos['.-..']='L'
mos['--']='M'
mos['-.']='N'
mos['---']='O'
mos['.--.']='P'
mos['--.-']='Q'
mos['.-.']='R'
mos['...']='S'
mos['-']='T'
mos['..-']='U'
mos['...-']='V'
mos['.--']='W'
mos['-..-']='X'
mos['-.--']='Y'
mos['--..']='Z'
mos['.----']='1'
mos['..---']='2'
mos['...--']='3'
mos['....-']='4'
mos['.....']='5'
mos['-....']='6'
mos['--...']='7'
mos['---..']='8'
mos['----.']='9'
mos['-----']='0'
mos['--..--']=','
mos['.-.-.-']='.'
mos['..--..']='?'
mos['---...']=':'
mos['-....-']='-'
mos['.--.-.']='@'

n=int(sys_input())
for x in sys_input().rstrip().split():
    print(mos[x],end="")
